export enum TransactionCategory {
  INCOME_FROM_CLIENTS = 'INCOME_FROM_CLIENTS',
  ONLINE_SALES = 'ONLINE_SALES',
  ADVERTISING_EXPENSES = 'ADVERTISING_EXPENSES',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  TRANSPORT = 'TRANSPORT',
  PAYROLL = 'PAYROLL',
  TRAVEL = 'TRAVEL',
  OFFICE = 'OFFICE',
  UTILITIES = 'UTILITIES',
  TAXES = 'TAXES',
  OTHER = 'OTHER',
}